@Autenticador_HostAddress = https://localhost:7275

###

# @name login
POST {{Autenticador_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "username": "testuser",
  "password": "12345678"
}

###

# @name refresh
POST {{Autenticador_HostAddress}}/api/auth/refresh
Content-Type: application/json

###

POST {{Autenticador_HostAddress}}/api/auth/logout
Content-Type: application/json

###

POST {{Autenticador_HostAddress}}/api/auth/logout-all
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

###